name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Debug APK
      run: ./gradlew assembleFdroidDebug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
          name: nightly-debug.apk
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
    - name: Send Telegram message
      run: |
          printf  printf '<b>Nowy build nightly!</b>\nZbudowany z commitu: ${{ github.event.head_commit.message }}\n\nPobierz z: https://github.com/wezuwiusz/neowulkanowy/actions/workflows/nightly-apk.yml?query=is:success' > tg.html
          TEXT=$(< "./tg.html")
          curl -s "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendmessage" --data "text=${TEXT}&chat_id=-1002156238140&parse_mode=HTML&disable_web_page_preview=True" > /dev/null
